package com.alipay.usercenter.common.dal.auto.daointerface;

import com.alipay.usercenter.common.dal.auto.dataobject.AutoReloadConfigDO;
import com.alipay.usercenter.common.dal.auto.dataobject.AutoReloadConfigDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AutoReloadConfigDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_reload_config
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    long countByExample(AutoReloadConfigDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_reload_config
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    int deleteByExample(AutoReloadConfigDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_reload_config
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    int deleteByPrimaryKey(Object configId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_reload_config
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    int insert(AutoReloadConfigDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_reload_config
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    int insertSelective(AutoReloadConfigDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_reload_config
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    List<AutoReloadConfigDO> selectByExample(AutoReloadConfigDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_reload_config
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    AutoReloadConfigDO selectByPrimaryKey(Object configId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_reload_config
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    int updateByExampleSelective(@Param("row") AutoReloadConfigDO row, @Param("example") AutoReloadConfigDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_reload_config
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    int updateByExample(@Param("row") AutoReloadConfigDO row, @Param("example") AutoReloadConfigDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_reload_config
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    int updateByPrimaryKeySelective(AutoReloadConfigDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_reload_config
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    int updateByPrimaryKey(AutoReloadConfigDO row);
}