package com.alipay.usercenter.common.dal.auto.daointerface;

import com.alipay.usercenter.common.dal.auto.dataobject.UserCardProviderDO;
import com.alipay.usercenter.common.dal.auto.dataobject.UserCardProviderDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserCardProviderDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_provider
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    long countByExample(UserCardProviderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_provider
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    int deleteByExample(UserCardProviderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_provider
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    int deleteByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_provider
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    int insert(UserCardProviderDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_provider
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    int insertSelective(UserCardProviderDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_provider
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    List<UserCardProviderDO> selectByExample(UserCardProviderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_provider
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    UserCardProviderDO selectByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_provider
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    int updateByExampleSelective(@Param("row") UserCardProviderDO row, @Param("example") UserCardProviderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_provider
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    int updateByExample(@Param("row") UserCardProviderDO row, @Param("example") UserCardProviderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_provider
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    int updateByPrimaryKeySelective(UserCardProviderDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_provider
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    int updateByPrimaryKey(UserCardProviderDO row);
}