package com.alipay.usercenter.common.dal.auto.daointerface;

import com.alipay.usercenter.common.dal.auto.dataobject.UserInfoDO;
import com.alipay.usercenter.common.dal.auto.dataobject.UserInfoDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Mar 26 19:13:56 AEDT 2026
     */
    long countByExample(UserInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Mar 26 19:13:56 AEDT 2026
     */
    int deleteByExample(UserInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Mar 26 19:13:56 AEDT 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Mar 26 19:13:56 AEDT 2026
     */
    int insert(UserInfoDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Mar 26 19:13:56 AEDT 2026
     */
    int insertSelective(UserInfoDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Mar 26 19:13:56 AEDT 2026
     */
    List<UserInfoDO> selectByExample(UserInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Mar 26 19:13:56 AEDT 2026
     */
    UserInfoDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Mar 26 19:13:56 AEDT 2026
     */
    int updateByExampleSelective(@Param("row") UserInfoDO row, @Param("example") UserInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Mar 26 19:13:56 AEDT 2026
     */
    int updateByExample(@Param("row") UserInfoDO row, @Param("example") UserInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Mar 26 19:13:56 AEDT 2026
     */
    int updateByPrimaryKeySelective(UserInfoDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Mar 26 19:13:56 AEDT 2026
     */
    int updateByPrimaryKey(UserInfoDO row);
}