package com.alipay.usercenter.common.dal.auto.daointerface;

import com.alipay.usercenter.common.dal.auto.dataobject.UserInfoDetailDO;
import com.alipay.usercenter.common.dal.auto.dataobject.UserInfoDetailDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserInfoDetailDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_detail
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    long countByExample(UserInfoDetailDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_detail
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    int deleteByExample(UserInfoDetailDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_detail
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    int deleteByPrimaryKey(Long userDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_detail
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    int insert(UserInfoDetailDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_detail
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    int insertSelective(UserInfoDetailDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_detail
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    List<UserInfoDetailDO> selectByExample(UserInfoDetailDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_detail
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    UserInfoDetailDO selectByPrimaryKey(Long userDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_detail
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    int updateByExampleSelective(@Param("row") UserInfoDetailDO row, @Param("example") UserInfoDetailDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_detail
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    int updateByExample(@Param("row") UserInfoDetailDO row, @Param("example") UserInfoDetailDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_detail
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    int updateByPrimaryKeySelective(UserInfoDetailDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_detail
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    int updateByPrimaryKey(UserInfoDetailDO row);
}