package com.alipay.usercenter.common.dal.auto.daointerface;

import com.alipay.usercenter.common.dal.auto.dataobject.UserCardDetailDO;
import com.alipay.usercenter.common.dal.auto.dataobject.UserCardDetailDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserCardDetailDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_detail
     *
     * @mbg.generated Sun Apr 05 19:40:51 AEST 2026
     */
    long countByExample(UserCardDetailDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_detail
     *
     * @mbg.generated Sun Apr 05 19:40:51 AEST 2026
     */
    int deleteByExample(UserCardDetailDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_detail
     *
     * @mbg.generated Sun Apr 05 19:40:51 AEST 2026
     */
    int deleteByPrimaryKey(Object userCardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_detail
     *
     * @mbg.generated Sun Apr 05 19:40:51 AEST 2026
     */
    int insert(UserCardDetailDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_detail
     *
     * @mbg.generated Sun Apr 05 19:40:51 AEST 2026
     */
    int insertSelective(UserCardDetailDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_detail
     *
     * @mbg.generated Sun Apr 05 19:40:51 AEST 2026
     */
    List<UserCardDetailDO> selectByExample(UserCardDetailDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_detail
     *
     * @mbg.generated Sun Apr 05 19:40:51 AEST 2026
     */
    UserCardDetailDO selectByPrimaryKey(Object userCardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_detail
     *
     * @mbg.generated Sun Apr 05 19:40:51 AEST 2026
     */
    int updateByExampleSelective(@Param("row") UserCardDetailDO row, @Param("example") UserCardDetailDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_detail
     *
     * @mbg.generated Sun Apr 05 19:40:51 AEST 2026
     */
    int updateByExample(@Param("row") UserCardDetailDO row, @Param("example") UserCardDetailDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_detail
     *
     * @mbg.generated Sun Apr 05 19:40:51 AEST 2026
     */
    int updateByPrimaryKeySelective(UserCardDetailDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_detail
     *
     * @mbg.generated Sun Apr 05 19:40:51 AEST 2026
     */
    int updateByPrimaryKey(UserCardDetailDO row);
}