package com.alipay.usercenter.common.dal.auto.daointerface;

import com.alipay.usercenter.common.dal.auto.dataobject.UserAuthDO;
import com.alipay.usercenter.common.dal.auto.dataobject.UserAuthDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserAuthDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    long countByExample(UserAuthDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    int deleteByExample(UserAuthDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    int deleteByPrimaryKey(Long authId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    int insert(UserAuthDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    int insertSelective(UserAuthDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    List<UserAuthDO> selectByExample(UserAuthDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    UserAuthDO selectByPrimaryKey(Long authId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    int updateByExampleSelective(@Param("row") UserAuthDO row, @Param("example") UserAuthDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    int updateByExample(@Param("row") UserAuthDO row, @Param("example") UserAuthDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    int updateByPrimaryKeySelective(UserAuthDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    int updateByPrimaryKey(UserAuthDO row);
}