package com.alipay.usercenter.common.dal.auto.daointerface;

import com.alipay.usercenter.common.dal.auto.dataobject.UserSessionDO;
import com.alipay.usercenter.common.dal.auto.dataobject.UserSessionDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserSessionDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_session
     *
     * @mbg.generated Mon Dec 08 00:29:26 MYT 2025
     */
    long countByExample(UserSessionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_session
     *
     * @mbg.generated Mon Dec 08 00:29:26 MYT 2025
     */
    int deleteByExample(UserSessionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_session
     *
     * @mbg.generated Mon Dec 08 00:29:26 MYT 2025
     */
    int deleteByPrimaryKey(Long sessionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_session
     *
     * @mbg.generated Mon Dec 08 00:29:26 MYT 2025
     */
    int insert(UserSessionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_session
     *
     * @mbg.generated Mon Dec 08 00:29:26 MYT 2025
     */
    int insertSelective(UserSessionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_session
     *
     * @mbg.generated Mon Dec 08 00:29:26 MYT 2025
     */
    List<UserSessionDO> selectByExample(UserSessionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_session
     *
     * @mbg.generated Mon Dec 08 00:29:26 MYT 2025
     */
    UserSessionDO selectByPrimaryKey(Long sessionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_session
     *
     * @mbg.generated Mon Dec 08 00:29:26 MYT 2025
     */
    int updateByExampleSelective(@Param("row") UserSessionDO row, @Param("example") UserSessionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_session
     *
     * @mbg.generated Mon Dec 08 00:29:26 MYT 2025
     */
    int updateByExample(@Param("row") UserSessionDO row, @Param("example") UserSessionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_session
     *
     * @mbg.generated Mon Dec 08 00:29:26 MYT 2025
     */
    int updateByPrimaryKeySelective(UserSessionDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_session
     *
     * @mbg.generated Mon Dec 08 00:29:26 MYT 2025
     */
    int updateByPrimaryKey(UserSessionDO row);
}