package com.alipay.usercenter.core.model;

import java.util.Date;

public class UserCardDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_card_detail.user_card_id
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    private Object userCardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_card_detail.user_id
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_card_detail.card_type
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    private String cardType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_card_detail.card_network
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    private String cardNetwork;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_card_detail.last_four
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    private String lastFour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_card_detail.expiry_month
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    private Short expiryMonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_card_detail.expiry_year
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    private Short expiryYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_card_detail.provider
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    private String provider;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_card_detail.provider_token
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    private String providerToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_card_detail.provider_customer_id
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    private String providerCustomerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_card_detail.cardholder_name
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    private String cardholderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_card_detail.is_default
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    private Boolean isDefault;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_card_detail.status
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_card_detail.gmt_create
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_card_detail.gmt_modified
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_card_detail.user_card_id
     *
     * @return the value of user_card_detail.user_card_id
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    public Object getUserCardId() {
        return userCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_card_detail.user_card_id
     *
     * @param userCardId the value for user_card_detail.user_card_id
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    public void setUserCardId(Object userCardId) {
        this.userCardId = userCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_card_detail.user_id
     *
     * @return the value of user_card_detail.user_id
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_card_detail.user_id
     *
     * @param userId the value for user_card_detail.user_id
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_card_detail.card_type
     *
     * @return the value of user_card_detail.card_type
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_card_detail.card_type
     *
     * @param cardType the value for user_card_detail.card_type
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    public void setCardType(String cardType) {
        this.cardType = cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_card_detail.card_network
     *
     * @return the value of user_card_detail.card_network
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    public String getCardNetwork() {
        return cardNetwork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_card_detail.card_network
     *
     * @param cardNetwork the value for user_card_detail.card_network
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    public void setCardNetwork(String cardNetwork) {
        this.cardNetwork = cardNetwork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_card_detail.last_four
     *
     * @return the value of user_card_detail.last_four
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    public String getLastFour() {
        return lastFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_card_detail.last_four
     *
     * @param lastFour the value for user_card_detail.last_four
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    public void setLastFour(String lastFour) {
        this.lastFour = lastFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_card_detail.expiry_month
     *
     * @return the value of user_card_detail.expiry_month
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    public Short getExpiryMonth() {
        return expiryMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_card_detail.expiry_month
     *
     * @param expiryMonth the value for user_card_detail.expiry_month
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    public void setExpiryMonth(Short expiryMonth) {
        this.expiryMonth = expiryMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_card_detail.expiry_year
     *
     * @return the value of user_card_detail.expiry_year
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    public Short getExpiryYear() {
        return expiryYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_card_detail.expiry_year
     *
     * @param expiryYear the value for user_card_detail.expiry_year
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    public void setExpiryYear(Short expiryYear) {
        this.expiryYear = expiryYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_card_detail.provider
     *
     * @return the value of user_card_detail.provider
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    public String getProvider() {
        return provider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_card_detail.provider
     *
     * @param provider the value for user_card_detail.provider
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    public void setProvider(String provider) {
        this.provider = provider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_card_detail.provider_token
     *
     * @return the value of user_card_detail.provider_token
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    public String getProviderToken() {
        return providerToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_card_detail.provider_token
     *
     * @param providerToken the value for user_card_detail.provider_token
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    public void setProviderToken(String providerToken) {
        this.providerToken = providerToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_card_detail.provider_customer_id
     *
     * @return the value of user_card_detail.provider_customer_id
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    public String getProviderCustomerId() {
        return providerCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_card_detail.provider_customer_id
     *
     * @param providerCustomerId the value for user_card_detail.provider_customer_id
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    public void setProviderCustomerId(String providerCustomerId) {
        this.providerCustomerId = providerCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_card_detail.cardholder_name
     *
     * @return the value of user_card_detail.cardholder_name
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    public String getCardholderName() {
        return cardholderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_card_detail.cardholder_name
     *
     * @param cardholderName the value for user_card_detail.cardholder_name
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    public void setCardholderName(String cardholderName) {
        this.cardholderName = cardholderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_card_detail.is_default
     *
     * @return the value of user_card_detail.is_default
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    public Boolean getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_card_detail.is_default
     *
     * @param isDefault the value for user_card_detail.is_default
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    public void setIsDefault(Boolean isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_card_detail.status
     *
     * @return the value of user_card_detail.status
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_card_detail.status
     *
     * @param status the value for user_card_detail.status
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_card_detail.gmt_create
     *
     * @return the value of user_card_detail.gmt_create
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_card_detail.gmt_create
     *
     * @param gmtCreate the value for user_card_detail.gmt_create
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_card_detail.gmt_modified
     *
     * @return the value of user_card_detail.gmt_modified
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_card_detail.gmt_modified
     *
     * @param gmtModified the value for user_card_detail.gmt_modified
     *
     * @mbg.generated Thu Apr 02 15:44:32 AEDT 2026
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}