package com.alipay.usercenter.core.model;

import java.util.Date;

/**
 * @author adam
 * @date 2/4/2026 3:30 PM
 */
public class UserCardProvider {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_card_provider.id
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    private Object id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_card_provider.user_id
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_card_provider.provider
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    private String provider;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_card_provider.provider_customer_id
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    private String providerCustomerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_card_provider.status
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_card_provider.gmt_create
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_card_provider.gmt_modified
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_card_provider.id
     *
     * @return the value of user_card_provider.id
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    public Object getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_card_provider.id
     *
     * @param id the value for user_card_provider.id
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    public void setId(Object id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_card_provider.user_id
     *
     * @return the value of user_card_provider.user_id
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_card_provider.user_id
     *
     * @param userId the value for user_card_provider.user_id
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_card_provider.provider
     *
     * @return the value of user_card_provider.provider
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    public String getProvider() {
        return provider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_card_provider.provider
     *
     * @param provider the value for user_card_provider.provider
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    public void setProvider(String provider) {
        this.provider = provider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_card_provider.provider_customer_id
     *
     * @return the value of user_card_provider.provider_customer_id
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    public String getProviderCustomerId() {
        return providerCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_card_provider.provider_customer_id
     *
     * @param providerCustomerId the value for user_card_provider.provider_customer_id
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    public void setProviderCustomerId(String providerCustomerId) {
        this.providerCustomerId = providerCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_card_provider.status
     *
     * @return the value of user_card_provider.status
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_card_provider.status
     *
     * @param status the value for user_card_provider.status
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_card_provider.gmt_create
     *
     * @return the value of user_card_provider.gmt_create
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_card_provider.gmt_create
     *
     * @param gmtCreate the value for user_card_provider.gmt_create
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_card_provider.gmt_modified
     *
     * @return the value of user_card_provider.gmt_modified
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_card_provider.gmt_modified
     *
     * @param gmtModified the value for user_card_provider.gmt_modified
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}