package com.alipay.usercenter.common.dal.auto.dataobject;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AutoReloadConfigDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auto_reload_config
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auto_reload_config
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auto_reload_config
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_reload_config
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    public AutoReloadConfigDOExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_reload_config
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_reload_config
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_reload_config
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_reload_config
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_reload_config
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_reload_config
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_reload_config
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_reload_config
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_reload_config
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_reload_config
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table auto_reload_config
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andConfigIdIsNull() {
            addCriterion("config_id is null");
            return (Criteria) this;
        }

        public Criteria andConfigIdIsNotNull() {
            addCriterion("config_id is not null");
            return (Criteria) this;
        }

        public Criteria andConfigIdEqualTo(Object value) {
            addCriterion("config_id =", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdNotEqualTo(Object value) {
            addCriterion("config_id <>", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdGreaterThan(Object value) {
            addCriterion("config_id >", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdGreaterThanOrEqualTo(Object value) {
            addCriterion("config_id >=", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdLessThan(Object value) {
            addCriterion("config_id <", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdLessThanOrEqualTo(Object value) {
            addCriterion("config_id <=", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdIn(List<Object> values) {
            addCriterion("config_id in", values, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdNotIn(List<Object> values) {
            addCriterion("config_id not in", values, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdBetween(Object value1, Object value2) {
            addCriterion("config_id between", value1, value2, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdNotBetween(Object value1, Object value2) {
            addCriterion("config_id not between", value1, value2, "configId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserCardIdIsNull() {
            addCriterion("user_card_id is null");
            return (Criteria) this;
        }

        public Criteria andUserCardIdIsNotNull() {
            addCriterion("user_card_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserCardIdEqualTo(Object value) {
            addCriterion("user_card_id =", value, "userCardId");
            return (Criteria) this;
        }

        public Criteria andUserCardIdNotEqualTo(Object value) {
            addCriterion("user_card_id <>", value, "userCardId");
            return (Criteria) this;
        }

        public Criteria andUserCardIdGreaterThan(Object value) {
            addCriterion("user_card_id >", value, "userCardId");
            return (Criteria) this;
        }

        public Criteria andUserCardIdGreaterThanOrEqualTo(Object value) {
            addCriterion("user_card_id >=", value, "userCardId");
            return (Criteria) this;
        }

        public Criteria andUserCardIdLessThan(Object value) {
            addCriterion("user_card_id <", value, "userCardId");
            return (Criteria) this;
        }

        public Criteria andUserCardIdLessThanOrEqualTo(Object value) {
            addCriterion("user_card_id <=", value, "userCardId");
            return (Criteria) this;
        }

        public Criteria andUserCardIdIn(List<Object> values) {
            addCriterion("user_card_id in", values, "userCardId");
            return (Criteria) this;
        }

        public Criteria andUserCardIdNotIn(List<Object> values) {
            addCriterion("user_card_id not in", values, "userCardId");
            return (Criteria) this;
        }

        public Criteria andUserCardIdBetween(Object value1, Object value2) {
            addCriterion("user_card_id between", value1, value2, "userCardId");
            return (Criteria) this;
        }

        public Criteria andUserCardIdNotBetween(Object value1, Object value2) {
            addCriterion("user_card_id not between", value1, value2, "userCardId");
            return (Criteria) this;
        }

        public Criteria andIsActiveIsNull() {
            addCriterion("is_active is null");
            return (Criteria) this;
        }

        public Criteria andIsActiveIsNotNull() {
            addCriterion("is_active is not null");
            return (Criteria) this;
        }

        public Criteria andIsActiveEqualTo(Boolean value) {
            addCriterion("is_active =", value, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveNotEqualTo(Boolean value) {
            addCriterion("is_active <>", value, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveGreaterThan(Boolean value) {
            addCriterion("is_active >", value, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_active >=", value, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveLessThan(Boolean value) {
            addCriterion("is_active <", value, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveLessThanOrEqualTo(Boolean value) {
            addCriterion("is_active <=", value, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveIn(List<Boolean> values) {
            addCriterion("is_active in", values, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveNotIn(List<Boolean> values) {
            addCriterion("is_active not in", values, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveBetween(Boolean value1, Boolean value2) {
            addCriterion("is_active between", value1, value2, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_active not between", value1, value2, "isActive");
            return (Criteria) this;
        }

        public Criteria andThresholdAmountIsNull() {
            addCriterion("threshold_amount is null");
            return (Criteria) this;
        }

        public Criteria andThresholdAmountIsNotNull() {
            addCriterion("threshold_amount is not null");
            return (Criteria) this;
        }

        public Criteria andThresholdAmountEqualTo(BigDecimal value) {
            addCriterion("threshold_amount =", value, "thresholdAmount");
            return (Criteria) this;
        }

        public Criteria andThresholdAmountNotEqualTo(BigDecimal value) {
            addCriterion("threshold_amount <>", value, "thresholdAmount");
            return (Criteria) this;
        }

        public Criteria andThresholdAmountGreaterThan(BigDecimal value) {
            addCriterion("threshold_amount >", value, "thresholdAmount");
            return (Criteria) this;
        }

        public Criteria andThresholdAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("threshold_amount >=", value, "thresholdAmount");
            return (Criteria) this;
        }

        public Criteria andThresholdAmountLessThan(BigDecimal value) {
            addCriterion("threshold_amount <", value, "thresholdAmount");
            return (Criteria) this;
        }

        public Criteria andThresholdAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("threshold_amount <=", value, "thresholdAmount");
            return (Criteria) this;
        }

        public Criteria andThresholdAmountIn(List<BigDecimal> values) {
            addCriterion("threshold_amount in", values, "thresholdAmount");
            return (Criteria) this;
        }

        public Criteria andThresholdAmountNotIn(List<BigDecimal> values) {
            addCriterion("threshold_amount not in", values, "thresholdAmount");
            return (Criteria) this;
        }

        public Criteria andThresholdAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("threshold_amount between", value1, value2, "thresholdAmount");
            return (Criteria) this;
        }

        public Criteria andThresholdAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("threshold_amount not between", value1, value2, "thresholdAmount");
            return (Criteria) this;
        }

        public Criteria andReloadAmountIsNull() {
            addCriterion("reload_amount is null");
            return (Criteria) this;
        }

        public Criteria andReloadAmountIsNotNull() {
            addCriterion("reload_amount is not null");
            return (Criteria) this;
        }

        public Criteria andReloadAmountEqualTo(BigDecimal value) {
            addCriterion("reload_amount =", value, "reloadAmount");
            return (Criteria) this;
        }

        public Criteria andReloadAmountNotEqualTo(BigDecimal value) {
            addCriterion("reload_amount <>", value, "reloadAmount");
            return (Criteria) this;
        }

        public Criteria andReloadAmountGreaterThan(BigDecimal value) {
            addCriterion("reload_amount >", value, "reloadAmount");
            return (Criteria) this;
        }

        public Criteria andReloadAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("reload_amount >=", value, "reloadAmount");
            return (Criteria) this;
        }

        public Criteria andReloadAmountLessThan(BigDecimal value) {
            addCriterion("reload_amount <", value, "reloadAmount");
            return (Criteria) this;
        }

        public Criteria andReloadAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("reload_amount <=", value, "reloadAmount");
            return (Criteria) this;
        }

        public Criteria andReloadAmountIn(List<BigDecimal> values) {
            addCriterion("reload_amount in", values, "reloadAmount");
            return (Criteria) this;
        }

        public Criteria andReloadAmountNotIn(List<BigDecimal> values) {
            addCriterion("reload_amount not in", values, "reloadAmount");
            return (Criteria) this;
        }

        public Criteria andReloadAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("reload_amount between", value1, value2, "reloadAmount");
            return (Criteria) this;
        }

        public Criteria andReloadAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("reload_amount not between", value1, value2, "reloadAmount");
            return (Criteria) this;
        }

        public Criteria andIsReloadInFlightIsNull() {
            addCriterion("is_reload_in_flight is null");
            return (Criteria) this;
        }

        public Criteria andIsReloadInFlightIsNotNull() {
            addCriterion("is_reload_in_flight is not null");
            return (Criteria) this;
        }

        public Criteria andIsReloadInFlightEqualTo(Boolean value) {
            addCriterion("is_reload_in_flight =", value, "isReloadInFlight");
            return (Criteria) this;
        }

        public Criteria andIsReloadInFlightNotEqualTo(Boolean value) {
            addCriterion("is_reload_in_flight <>", value, "isReloadInFlight");
            return (Criteria) this;
        }

        public Criteria andIsReloadInFlightGreaterThan(Boolean value) {
            addCriterion("is_reload_in_flight >", value, "isReloadInFlight");
            return (Criteria) this;
        }

        public Criteria andIsReloadInFlightGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_reload_in_flight >=", value, "isReloadInFlight");
            return (Criteria) this;
        }

        public Criteria andIsReloadInFlightLessThan(Boolean value) {
            addCriterion("is_reload_in_flight <", value, "isReloadInFlight");
            return (Criteria) this;
        }

        public Criteria andIsReloadInFlightLessThanOrEqualTo(Boolean value) {
            addCriterion("is_reload_in_flight <=", value, "isReloadInFlight");
            return (Criteria) this;
        }

        public Criteria andIsReloadInFlightIn(List<Boolean> values) {
            addCriterion("is_reload_in_flight in", values, "isReloadInFlight");
            return (Criteria) this;
        }

        public Criteria andIsReloadInFlightNotIn(List<Boolean> values) {
            addCriterion("is_reload_in_flight not in", values, "isReloadInFlight");
            return (Criteria) this;
        }

        public Criteria andIsReloadInFlightBetween(Boolean value1, Boolean value2) {
            addCriterion("is_reload_in_flight between", value1, value2, "isReloadInFlight");
            return (Criteria) this;
        }

        public Criteria andIsReloadInFlightNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_reload_in_flight not between", value1, value2, "isReloadInFlight");
            return (Criteria) this;
        }

        public Criteria andLastTriggeredAtIsNull() {
            addCriterion("last_triggered_at is null");
            return (Criteria) this;
        }

        public Criteria andLastTriggeredAtIsNotNull() {
            addCriterion("last_triggered_at is not null");
            return (Criteria) this;
        }

        public Criteria andLastTriggeredAtEqualTo(Date value) {
            addCriterion("last_triggered_at =", value, "lastTriggeredAt");
            return (Criteria) this;
        }

        public Criteria andLastTriggeredAtNotEqualTo(Date value) {
            addCriterion("last_triggered_at <>", value, "lastTriggeredAt");
            return (Criteria) this;
        }

        public Criteria andLastTriggeredAtGreaterThan(Date value) {
            addCriterion("last_triggered_at >", value, "lastTriggeredAt");
            return (Criteria) this;
        }

        public Criteria andLastTriggeredAtGreaterThanOrEqualTo(Date value) {
            addCriterion("last_triggered_at >=", value, "lastTriggeredAt");
            return (Criteria) this;
        }

        public Criteria andLastTriggeredAtLessThan(Date value) {
            addCriterion("last_triggered_at <", value, "lastTriggeredAt");
            return (Criteria) this;
        }

        public Criteria andLastTriggeredAtLessThanOrEqualTo(Date value) {
            addCriterion("last_triggered_at <=", value, "lastTriggeredAt");
            return (Criteria) this;
        }

        public Criteria andLastTriggeredAtIn(List<Date> values) {
            addCriterion("last_triggered_at in", values, "lastTriggeredAt");
            return (Criteria) this;
        }

        public Criteria andLastTriggeredAtNotIn(List<Date> values) {
            addCriterion("last_triggered_at not in", values, "lastTriggeredAt");
            return (Criteria) this;
        }

        public Criteria andLastTriggeredAtBetween(Date value1, Date value2) {
            addCriterion("last_triggered_at between", value1, value2, "lastTriggeredAt");
            return (Criteria) this;
        }

        public Criteria andLastTriggeredAtNotBetween(Date value1, Date value2) {
            addCriterion("last_triggered_at not between", value1, value2, "lastTriggeredAt");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andCurrencyIsNull() {
            addCriterion("currency is null");
            return (Criteria) this;
        }

        public Criteria andCurrencyIsNotNull() {
            addCriterion("currency is not null");
            return (Criteria) this;
        }

        public Criteria andCurrencyEqualTo(String value) {
            addCriterion("currency =", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyNotEqualTo(String value) {
            addCriterion("currency <>", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyGreaterThan(String value) {
            addCriterion("currency >", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyGreaterThanOrEqualTo(String value) {
            addCriterion("currency >=", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyLessThan(String value) {
            addCriterion("currency <", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyLessThanOrEqualTo(String value) {
            addCriterion("currency <=", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyLike(String value) {
            addCriterion("currency like", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyNotLike(String value) {
            addCriterion("currency not like", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyIn(List<String> values) {
            addCriterion("currency in", values, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyNotIn(List<String> values) {
            addCriterion("currency not in", values, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyBetween(String value1, String value2) {
            addCriterion("currency between", value1, value2, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyNotBetween(String value1, String value2) {
            addCriterion("currency not between", value1, value2, "currency");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table auto_reload_config
     *
     * @mbg.generated do_not_delete_during_merge Thu Apr 02 17:30:19 AEDT 2026
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table auto_reload_config
     *
     * @mbg.generated Thu Apr 02 17:30:19 AEDT 2026
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}