package com.alipay.usercenter.common.dal.auto.dataobject;

import java.math.BigDecimal;
import java.util.Date;

public class AutoReloadConfigDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_reload_config.config_id
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    private Object configId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_reload_config.user_id
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_reload_config.user_card_id
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    private Object userCardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_reload_config.is_active
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    private Boolean isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_reload_config.threshold_amount
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    private BigDecimal thresholdAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_reload_config.reload_amount
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    private BigDecimal reloadAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_reload_config.is_reload_in_flight
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    private Boolean isReloadInFlight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_reload_config.last_triggered_at
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    private Date lastTriggeredAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_reload_config.gmt_create
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_reload_config.gmt_modified
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_reload_config.currency
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    private String currency;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_reload_config.config_id
     *
     * @return the value of auto_reload_config.config_id
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    public Object getConfigId() {
        return configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_reload_config.config_id
     *
     * @param configId the value for auto_reload_config.config_id
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    public void setConfigId(Object configId) {
        this.configId = configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_reload_config.user_id
     *
     * @return the value of auto_reload_config.user_id
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_reload_config.user_id
     *
     * @param userId the value for auto_reload_config.user_id
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_reload_config.user_card_id
     *
     * @return the value of auto_reload_config.user_card_id
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    public Object getUserCardId() {
        return userCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_reload_config.user_card_id
     *
     * @param userCardId the value for auto_reload_config.user_card_id
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    public void setUserCardId(Object userCardId) {
        this.userCardId = userCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_reload_config.is_active
     *
     * @return the value of auto_reload_config.is_active
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_reload_config.is_active
     *
     * @param isActive the value for auto_reload_config.is_active
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_reload_config.threshold_amount
     *
     * @return the value of auto_reload_config.threshold_amount
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    public BigDecimal getThresholdAmount() {
        return thresholdAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_reload_config.threshold_amount
     *
     * @param thresholdAmount the value for auto_reload_config.threshold_amount
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    public void setThresholdAmount(BigDecimal thresholdAmount) {
        this.thresholdAmount = thresholdAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_reload_config.reload_amount
     *
     * @return the value of auto_reload_config.reload_amount
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    public BigDecimal getReloadAmount() {
        return reloadAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_reload_config.reload_amount
     *
     * @param reloadAmount the value for auto_reload_config.reload_amount
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    public void setReloadAmount(BigDecimal reloadAmount) {
        this.reloadAmount = reloadAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_reload_config.is_reload_in_flight
     *
     * @return the value of auto_reload_config.is_reload_in_flight
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    public Boolean getIsReloadInFlight() {
        return isReloadInFlight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_reload_config.is_reload_in_flight
     *
     * @param isReloadInFlight the value for auto_reload_config.is_reload_in_flight
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    public void setIsReloadInFlight(Boolean isReloadInFlight) {
        this.isReloadInFlight = isReloadInFlight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_reload_config.last_triggered_at
     *
     * @return the value of auto_reload_config.last_triggered_at
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    public Date getLastTriggeredAt() {
        return lastTriggeredAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_reload_config.last_triggered_at
     *
     * @param lastTriggeredAt the value for auto_reload_config.last_triggered_at
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    public void setLastTriggeredAt(Date lastTriggeredAt) {
        this.lastTriggeredAt = lastTriggeredAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_reload_config.gmt_create
     *
     * @return the value of auto_reload_config.gmt_create
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_reload_config.gmt_create
     *
     * @param gmtCreate the value for auto_reload_config.gmt_create
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_reload_config.gmt_modified
     *
     * @return the value of auto_reload_config.gmt_modified
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_reload_config.gmt_modified
     *
     * @param gmtModified the value for auto_reload_config.gmt_modified
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_reload_config.currency
     *
     * @return the value of auto_reload_config.currency
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_reload_config.currency
     *
     * @param currency the value for auto_reload_config.currency
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }
}