package com.alipay.usercenter.common.dal.auto.dataobject;

import java.util.Date;

public class UserAuthDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.auth_id
     *
     * @mbg.generated Tue Mar 10 15:07:45 AEDT 2026
     */
    private Object authId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.user_id
     *
     * @mbg.generated Tue Mar 10 15:07:45 AEDT 2026
     */
    private Object userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.auth_type
     *
     * @mbg.generated Tue Mar 10 15:07:45 AEDT 2026
     */
    private String authType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.credential_hash
     *
     * @mbg.generated Tue Mar 10 15:07:45 AEDT 2026
     */
    private String credentialHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.failed_attempts
     *
     * @mbg.generated Tue Mar 10 15:07:45 AEDT 2026
     */
    private Integer failedAttempts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.lock_until
     *
     * @mbg.generated Tue Mar 10 15:07:45 AEDT 2026
     */
    private Date lockUntil;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.is_active
     *
     * @mbg.generated Tue Mar 10 15:07:45 AEDT 2026
     */
    private Boolean isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.last_used
     *
     * @mbg.generated Tue Mar 10 15:07:45 AEDT 2026
     */
    private Date lastUsed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.gmt_create
     *
     * @mbg.generated Tue Mar 10 15:07:45 AEDT 2026
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.gmt_modified
     *
     * @mbg.generated Tue Mar 10 15:07:45 AEDT 2026
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.auth_id
     *
     * @return the value of user_auth.auth_id
     *
     * @mbg.generated Tue Mar 10 15:07:45 AEDT 2026
     */
    public Object getAuthId() {
        return authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.auth_id
     *
     * @param authId the value for user_auth.auth_id
     *
     * @mbg.generated Tue Mar 10 15:07:45 AEDT 2026
     */
    public void setAuthId(Object authId) {
        this.authId = authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.user_id
     *
     * @return the value of user_auth.user_id
     *
     * @mbg.generated Tue Mar 10 15:07:45 AEDT 2026
     */
    public Object getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.user_id
     *
     * @param userId the value for user_auth.user_id
     *
     * @mbg.generated Tue Mar 10 15:07:45 AEDT 2026
     */
    public void setUserId(Object userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.auth_type
     *
     * @return the value of user_auth.auth_type
     *
     * @mbg.generated Tue Mar 10 15:07:45 AEDT 2026
     */
    public String getAuthType() {
        return authType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.auth_type
     *
     * @param authType the value for user_auth.auth_type
     *
     * @mbg.generated Tue Mar 10 15:07:45 AEDT 2026
     */
    public void setAuthType(String authType) {
        this.authType = authType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.credential_hash
     *
     * @return the value of user_auth.credential_hash
     *
     * @mbg.generated Tue Mar 10 15:07:45 AEDT 2026
     */
    public String getCredentialHash() {
        return credentialHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.credential_hash
     *
     * @param credentialHash the value for user_auth.credential_hash
     *
     * @mbg.generated Tue Mar 10 15:07:45 AEDT 2026
     */
    public void setCredentialHash(String credentialHash) {
        this.credentialHash = credentialHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.failed_attempts
     *
     * @return the value of user_auth.failed_attempts
     *
     * @mbg.generated Tue Mar 10 15:07:45 AEDT 2026
     */
    public Integer getFailedAttempts() {
        return failedAttempts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.failed_attempts
     *
     * @param failedAttempts the value for user_auth.failed_attempts
     *
     * @mbg.generated Tue Mar 10 15:07:45 AEDT 2026
     */
    public void setFailedAttempts(Integer failedAttempts) {
        this.failedAttempts = failedAttempts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.lock_until
     *
     * @return the value of user_auth.lock_until
     *
     * @mbg.generated Tue Mar 10 15:07:45 AEDT 2026
     */
    public Date getLockUntil() {
        return lockUntil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.lock_until
     *
     * @param lockUntil the value for user_auth.lock_until
     *
     * @mbg.generated Tue Mar 10 15:07:45 AEDT 2026
     */
    public void setLockUntil(Date lockUntil) {
        this.lockUntil = lockUntil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.is_active
     *
     * @return the value of user_auth.is_active
     *
     * @mbg.generated Tue Mar 10 15:07:45 AEDT 2026
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.is_active
     *
     * @param isActive the value for user_auth.is_active
     *
     * @mbg.generated Tue Mar 10 15:07:45 AEDT 2026
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.last_used
     *
     * @return the value of user_auth.last_used
     *
     * @mbg.generated Tue Mar 10 15:07:45 AEDT 2026
     */
    public Date getLastUsed() {
        return lastUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.last_used
     *
     * @param lastUsed the value for user_auth.last_used
     *
     * @mbg.generated Tue Mar 10 15:07:45 AEDT 2026
     */
    public void setLastUsed(Date lastUsed) {
        this.lastUsed = lastUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.gmt_create
     *
     * @return the value of user_auth.gmt_create
     *
     * @mbg.generated Tue Mar 10 15:07:45 AEDT 2026
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.gmt_create
     *
     * @param gmtCreate the value for user_auth.gmt_create
     *
     * @mbg.generated Tue Mar 10 15:07:45 AEDT 2026
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.gmt_modified
     *
     * @return the value of user_auth.gmt_modified
     *
     * @mbg.generated Tue Mar 10 15:07:45 AEDT 2026
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.gmt_modified
     *
     * @param gmtModified the value for user_auth.gmt_modified
     *
     * @mbg.generated Tue Mar 10 15:07:45 AEDT 2026
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}