package com.alipay.usercenter.common.dal.auto.dataobject;

import java.util.Date;

public class UserInfoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbg.generated Mon Apr 06 00:57:12 AEST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_id
     *
     * @mbg.generated Mon Apr 06 00:57:12 AEST 2026
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.phone_no
     *
     * @mbg.generated Mon Apr 06 00:57:12 AEST 2026
     */
    private String phoneNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.status
     *
     * @mbg.generated Mon Apr 06 00:57:12 AEST 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.hashed_password
     *
     * @mbg.generated Mon Apr 06 00:57:12 AEST 2026
     */
    private String hashedPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.gmt_create
     *
     * @mbg.generated Mon Apr 06 00:57:12 AEST 2026
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.gmt_modified
     *
     * @mbg.generated Mon Apr 06 00:57:12 AEST 2026
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.contact_config
     *
     * @mbg.generated Mon Apr 06 00:57:12 AEST 2026
     */
    private Object contactConfig;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.ext_info
     *
     * @mbg.generated Mon Apr 06 00:57:12 AEST 2026
     */
    private Object extInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_name
     *
     * @mbg.generated Mon Apr 06 00:57:12 AEST 2026
     */
    private String userName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbg.generated Mon Apr 06 00:57:12 AEST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbg.generated Mon Apr 06 00:57:12 AEST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_id
     *
     * @return the value of user_info.user_id
     *
     * @mbg.generated Mon Apr 06 00:57:12 AEST 2026
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_id
     *
     * @param userId the value for user_info.user_id
     *
     * @mbg.generated Mon Apr 06 00:57:12 AEST 2026
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.phone_no
     *
     * @return the value of user_info.phone_no
     *
     * @mbg.generated Mon Apr 06 00:57:12 AEST 2026
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.phone_no
     *
     * @param phoneNo the value for user_info.phone_no
     *
     * @mbg.generated Mon Apr 06 00:57:12 AEST 2026
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.status
     *
     * @return the value of user_info.status
     *
     * @mbg.generated Mon Apr 06 00:57:12 AEST 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.status
     *
     * @param status the value for user_info.status
     *
     * @mbg.generated Mon Apr 06 00:57:12 AEST 2026
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.hashed_password
     *
     * @return the value of user_info.hashed_password
     *
     * @mbg.generated Mon Apr 06 00:57:12 AEST 2026
     */
    public String getHashedPassword() {
        return hashedPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.hashed_password
     *
     * @param hashedPassword the value for user_info.hashed_password
     *
     * @mbg.generated Mon Apr 06 00:57:12 AEST 2026
     */
    public void setHashedPassword(String hashedPassword) {
        this.hashedPassword = hashedPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.gmt_create
     *
     * @return the value of user_info.gmt_create
     *
     * @mbg.generated Mon Apr 06 00:57:12 AEST 2026
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.gmt_create
     *
     * @param gmtCreate the value for user_info.gmt_create
     *
     * @mbg.generated Mon Apr 06 00:57:12 AEST 2026
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.gmt_modified
     *
     * @return the value of user_info.gmt_modified
     *
     * @mbg.generated Mon Apr 06 00:57:12 AEST 2026
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.gmt_modified
     *
     * @param gmtModified the value for user_info.gmt_modified
     *
     * @mbg.generated Mon Apr 06 00:57:12 AEST 2026
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.contact_config
     *
     * @return the value of user_info.contact_config
     *
     * @mbg.generated Mon Apr 06 00:57:12 AEST 2026
     */
    public Object getContactConfig() {
        return contactConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.contact_config
     *
     * @param contactConfig the value for user_info.contact_config
     *
     * @mbg.generated Mon Apr 06 00:57:12 AEST 2026
     */
    public void setContactConfig(Object contactConfig) {
        this.contactConfig = contactConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.ext_info
     *
     * @return the value of user_info.ext_info
     *
     * @mbg.generated Mon Apr 06 00:57:12 AEST 2026
     */
    public Object getExtInfo() {
        return extInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.ext_info
     *
     * @param extInfo the value for user_info.ext_info
     *
     * @mbg.generated Mon Apr 06 00:57:12 AEST 2026
     */
    public void setExtInfo(Object extInfo) {
        this.extInfo = extInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_name
     *
     * @return the value of user_info.user_name
     *
     * @mbg.generated Mon Apr 06 00:57:12 AEST 2026
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_name
     *
     * @param userName the value for user_info.user_name
     *
     * @mbg.generated Mon Apr 06 00:57:12 AEST 2026
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }
}