package com.alipay.usercenter.common.dal.auto.dataobject;

import java.util.Date;

public class UserInfoDetailDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_detail.user_detail_id
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    private Long userDetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_detail.user_id
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_detail.email
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_detail.full_name
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    private String fullName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_detail.credit_card_hash
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    private String creditCardHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_detail.address
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_detail.date_of_birth
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    private Date dateOfBirth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_detail.profile_picture
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    private String profilePicture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_detail.gmt_create
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_detail.gmt_modified
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_detail.user_detail_id
     *
     * @return the value of user_info_detail.user_detail_id
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    public Long getUserDetailId() {
        return userDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_detail.user_detail_id
     *
     * @param userDetailId the value for user_info_detail.user_detail_id
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    public void setUserDetailId(Long userDetailId) {
        this.userDetailId = userDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_detail.user_id
     *
     * @return the value of user_info_detail.user_id
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_detail.user_id
     *
     * @param userId the value for user_info_detail.user_id
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_detail.email
     *
     * @return the value of user_info_detail.email
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_detail.email
     *
     * @param email the value for user_info_detail.email
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_detail.full_name
     *
     * @return the value of user_info_detail.full_name
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_detail.full_name
     *
     * @param fullName the value for user_info_detail.full_name
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_detail.credit_card_hash
     *
     * @return the value of user_info_detail.credit_card_hash
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    public String getCreditCardHash() {
        return creditCardHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_detail.credit_card_hash
     *
     * @param creditCardHash the value for user_info_detail.credit_card_hash
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    public void setCreditCardHash(String creditCardHash) {
        this.creditCardHash = creditCardHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_detail.address
     *
     * @return the value of user_info_detail.address
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_detail.address
     *
     * @param address the value for user_info_detail.address
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_detail.date_of_birth
     *
     * @return the value of user_info_detail.date_of_birth
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    public Date getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_detail.date_of_birth
     *
     * @param dateOfBirth the value for user_info_detail.date_of_birth
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_detail.profile_picture
     *
     * @return the value of user_info_detail.profile_picture
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    public String getProfilePicture() {
        return profilePicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_detail.profile_picture
     *
     * @param profilePicture the value for user_info_detail.profile_picture
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    public void setProfilePicture(String profilePicture) {
        this.profilePicture = profilePicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_detail.gmt_create
     *
     * @return the value of user_info_detail.gmt_create
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_detail.gmt_create
     *
     * @param gmtCreate the value for user_info_detail.gmt_create
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_detail.gmt_modified
     *
     * @return the value of user_info_detail.gmt_modified
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_detail.gmt_modified
     *
     * @param gmtModified the value for user_info_detail.gmt_modified
     *
     * @mbg.generated Mon Dec 08 00:24:33 MYT 2025
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}