package com.alipay.usercenter.common.dal.auto.dataobject;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserAuthDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_auth
     *
     * @mbg.generated Sun Apr 05 19:40:51 AEST 2026
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_auth
     *
     * @mbg.generated Sun Apr 05 19:40:51 AEST 2026
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_auth
     *
     * @mbg.generated Sun Apr 05 19:40:51 AEST 2026
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Sun Apr 05 19:40:51 AEST 2026
     */
    public UserAuthDOExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Sun Apr 05 19:40:51 AEST 2026
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Sun Apr 05 19:40:51 AEST 2026
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Sun Apr 05 19:40:51 AEST 2026
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Sun Apr 05 19:40:51 AEST 2026
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Sun Apr 05 19:40:51 AEST 2026
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Sun Apr 05 19:40:51 AEST 2026
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Sun Apr 05 19:40:51 AEST 2026
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Sun Apr 05 19:40:51 AEST 2026
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Sun Apr 05 19:40:51 AEST 2026
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Sun Apr 05 19:40:51 AEST 2026
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_auth
     *
     * @mbg.generated Sun Apr 05 19:40:51 AEST 2026
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAuthIdIsNull() {
            addCriterion("auth_id is null");
            return (Criteria) this;
        }

        public Criteria andAuthIdIsNotNull() {
            addCriterion("auth_id is not null");
            return (Criteria) this;
        }

        public Criteria andAuthIdEqualTo(Long value) {
            addCriterion("auth_id =", value, "authId");
            return (Criteria) this;
        }

        public Criteria andAuthIdNotEqualTo(Long value) {
            addCriterion("auth_id <>", value, "authId");
            return (Criteria) this;
        }

        public Criteria andAuthIdGreaterThan(Long value) {
            addCriterion("auth_id >", value, "authId");
            return (Criteria) this;
        }

        public Criteria andAuthIdGreaterThanOrEqualTo(Long value) {
            addCriterion("auth_id >=", value, "authId");
            return (Criteria) this;
        }

        public Criteria andAuthIdLessThan(Long value) {
            addCriterion("auth_id <", value, "authId");
            return (Criteria) this;
        }

        public Criteria andAuthIdLessThanOrEqualTo(Long value) {
            addCriterion("auth_id <=", value, "authId");
            return (Criteria) this;
        }

        public Criteria andAuthIdIn(List<Long> values) {
            addCriterion("auth_id in", values, "authId");
            return (Criteria) this;
        }

        public Criteria andAuthIdNotIn(List<Long> values) {
            addCriterion("auth_id not in", values, "authId");
            return (Criteria) this;
        }

        public Criteria andAuthIdBetween(Long value1, Long value2) {
            addCriterion("auth_id between", value1, value2, "authId");
            return (Criteria) this;
        }

        public Criteria andAuthIdNotBetween(Long value1, Long value2) {
            addCriterion("auth_id not between", value1, value2, "authId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andAuthTypeIsNull() {
            addCriterion("auth_type is null");
            return (Criteria) this;
        }

        public Criteria andAuthTypeIsNotNull() {
            addCriterion("auth_type is not null");
            return (Criteria) this;
        }

        public Criteria andAuthTypeEqualTo(String value) {
            addCriterion("auth_type =", value, "authType");
            return (Criteria) this;
        }

        public Criteria andAuthTypeNotEqualTo(String value) {
            addCriterion("auth_type <>", value, "authType");
            return (Criteria) this;
        }

        public Criteria andAuthTypeGreaterThan(String value) {
            addCriterion("auth_type >", value, "authType");
            return (Criteria) this;
        }

        public Criteria andAuthTypeGreaterThanOrEqualTo(String value) {
            addCriterion("auth_type >=", value, "authType");
            return (Criteria) this;
        }

        public Criteria andAuthTypeLessThan(String value) {
            addCriterion("auth_type <", value, "authType");
            return (Criteria) this;
        }

        public Criteria andAuthTypeLessThanOrEqualTo(String value) {
            addCriterion("auth_type <=", value, "authType");
            return (Criteria) this;
        }

        public Criteria andAuthTypeLike(String value) {
            addCriterion("auth_type like", value, "authType");
            return (Criteria) this;
        }

        public Criteria andAuthTypeNotLike(String value) {
            addCriterion("auth_type not like", value, "authType");
            return (Criteria) this;
        }

        public Criteria andAuthTypeIn(List<String> values) {
            addCriterion("auth_type in", values, "authType");
            return (Criteria) this;
        }

        public Criteria andAuthTypeNotIn(List<String> values) {
            addCriterion("auth_type not in", values, "authType");
            return (Criteria) this;
        }

        public Criteria andAuthTypeBetween(String value1, String value2) {
            addCriterion("auth_type between", value1, value2, "authType");
            return (Criteria) this;
        }

        public Criteria andAuthTypeNotBetween(String value1, String value2) {
            addCriterion("auth_type not between", value1, value2, "authType");
            return (Criteria) this;
        }

        public Criteria andCredentialHashIsNull() {
            addCriterion("credential_hash is null");
            return (Criteria) this;
        }

        public Criteria andCredentialHashIsNotNull() {
            addCriterion("credential_hash is not null");
            return (Criteria) this;
        }

        public Criteria andCredentialHashEqualTo(String value) {
            addCriterion("credential_hash =", value, "credentialHash");
            return (Criteria) this;
        }

        public Criteria andCredentialHashNotEqualTo(String value) {
            addCriterion("credential_hash <>", value, "credentialHash");
            return (Criteria) this;
        }

        public Criteria andCredentialHashGreaterThan(String value) {
            addCriterion("credential_hash >", value, "credentialHash");
            return (Criteria) this;
        }

        public Criteria andCredentialHashGreaterThanOrEqualTo(String value) {
            addCriterion("credential_hash >=", value, "credentialHash");
            return (Criteria) this;
        }

        public Criteria andCredentialHashLessThan(String value) {
            addCriterion("credential_hash <", value, "credentialHash");
            return (Criteria) this;
        }

        public Criteria andCredentialHashLessThanOrEqualTo(String value) {
            addCriterion("credential_hash <=", value, "credentialHash");
            return (Criteria) this;
        }

        public Criteria andCredentialHashLike(String value) {
            addCriterion("credential_hash like", value, "credentialHash");
            return (Criteria) this;
        }

        public Criteria andCredentialHashNotLike(String value) {
            addCriterion("credential_hash not like", value, "credentialHash");
            return (Criteria) this;
        }

        public Criteria andCredentialHashIn(List<String> values) {
            addCriterion("credential_hash in", values, "credentialHash");
            return (Criteria) this;
        }

        public Criteria andCredentialHashNotIn(List<String> values) {
            addCriterion("credential_hash not in", values, "credentialHash");
            return (Criteria) this;
        }

        public Criteria andCredentialHashBetween(String value1, String value2) {
            addCriterion("credential_hash between", value1, value2, "credentialHash");
            return (Criteria) this;
        }

        public Criteria andCredentialHashNotBetween(String value1, String value2) {
            addCriterion("credential_hash not between", value1, value2, "credentialHash");
            return (Criteria) this;
        }

        public Criteria andFailedAttemptsIsNull() {
            addCriterion("failed_attempts is null");
            return (Criteria) this;
        }

        public Criteria andFailedAttemptsIsNotNull() {
            addCriterion("failed_attempts is not null");
            return (Criteria) this;
        }

        public Criteria andFailedAttemptsEqualTo(Integer value) {
            addCriterion("failed_attempts =", value, "failedAttempts");
            return (Criteria) this;
        }

        public Criteria andFailedAttemptsNotEqualTo(Integer value) {
            addCriterion("failed_attempts <>", value, "failedAttempts");
            return (Criteria) this;
        }

        public Criteria andFailedAttemptsGreaterThan(Integer value) {
            addCriterion("failed_attempts >", value, "failedAttempts");
            return (Criteria) this;
        }

        public Criteria andFailedAttemptsGreaterThanOrEqualTo(Integer value) {
            addCriterion("failed_attempts >=", value, "failedAttempts");
            return (Criteria) this;
        }

        public Criteria andFailedAttemptsLessThan(Integer value) {
            addCriterion("failed_attempts <", value, "failedAttempts");
            return (Criteria) this;
        }

        public Criteria andFailedAttemptsLessThanOrEqualTo(Integer value) {
            addCriterion("failed_attempts <=", value, "failedAttempts");
            return (Criteria) this;
        }

        public Criteria andFailedAttemptsIn(List<Integer> values) {
            addCriterion("failed_attempts in", values, "failedAttempts");
            return (Criteria) this;
        }

        public Criteria andFailedAttemptsNotIn(List<Integer> values) {
            addCriterion("failed_attempts not in", values, "failedAttempts");
            return (Criteria) this;
        }

        public Criteria andFailedAttemptsBetween(Integer value1, Integer value2) {
            addCriterion("failed_attempts between", value1, value2, "failedAttempts");
            return (Criteria) this;
        }

        public Criteria andFailedAttemptsNotBetween(Integer value1, Integer value2) {
            addCriterion("failed_attempts not between", value1, value2, "failedAttempts");
            return (Criteria) this;
        }

        public Criteria andLockUntilIsNull() {
            addCriterion("lock_until is null");
            return (Criteria) this;
        }

        public Criteria andLockUntilIsNotNull() {
            addCriterion("lock_until is not null");
            return (Criteria) this;
        }

        public Criteria andLockUntilEqualTo(Date value) {
            addCriterion("lock_until =", value, "lockUntil");
            return (Criteria) this;
        }

        public Criteria andLockUntilNotEqualTo(Date value) {
            addCriterion("lock_until <>", value, "lockUntil");
            return (Criteria) this;
        }

        public Criteria andLockUntilGreaterThan(Date value) {
            addCriterion("lock_until >", value, "lockUntil");
            return (Criteria) this;
        }

        public Criteria andLockUntilGreaterThanOrEqualTo(Date value) {
            addCriterion("lock_until >=", value, "lockUntil");
            return (Criteria) this;
        }

        public Criteria andLockUntilLessThan(Date value) {
            addCriterion("lock_until <", value, "lockUntil");
            return (Criteria) this;
        }

        public Criteria andLockUntilLessThanOrEqualTo(Date value) {
            addCriterion("lock_until <=", value, "lockUntil");
            return (Criteria) this;
        }

        public Criteria andLockUntilIn(List<Date> values) {
            addCriterion("lock_until in", values, "lockUntil");
            return (Criteria) this;
        }

        public Criteria andLockUntilNotIn(List<Date> values) {
            addCriterion("lock_until not in", values, "lockUntil");
            return (Criteria) this;
        }

        public Criteria andLockUntilBetween(Date value1, Date value2) {
            addCriterion("lock_until between", value1, value2, "lockUntil");
            return (Criteria) this;
        }

        public Criteria andLockUntilNotBetween(Date value1, Date value2) {
            addCriterion("lock_until not between", value1, value2, "lockUntil");
            return (Criteria) this;
        }

        public Criteria andIsActiveIsNull() {
            addCriterion("is_active is null");
            return (Criteria) this;
        }

        public Criteria andIsActiveIsNotNull() {
            addCriterion("is_active is not null");
            return (Criteria) this;
        }

        public Criteria andIsActiveEqualTo(Boolean value) {
            addCriterion("is_active =", value, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveNotEqualTo(Boolean value) {
            addCriterion("is_active <>", value, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveGreaterThan(Boolean value) {
            addCriterion("is_active >", value, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_active >=", value, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveLessThan(Boolean value) {
            addCriterion("is_active <", value, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveLessThanOrEqualTo(Boolean value) {
            addCriterion("is_active <=", value, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveIn(List<Boolean> values) {
            addCriterion("is_active in", values, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveNotIn(List<Boolean> values) {
            addCriterion("is_active not in", values, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveBetween(Boolean value1, Boolean value2) {
            addCriterion("is_active between", value1, value2, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_active not between", value1, value2, "isActive");
            return (Criteria) this;
        }

        public Criteria andLastUsedIsNull() {
            addCriterion("last_used is null");
            return (Criteria) this;
        }

        public Criteria andLastUsedIsNotNull() {
            addCriterion("last_used is not null");
            return (Criteria) this;
        }

        public Criteria andLastUsedEqualTo(Date value) {
            addCriterion("last_used =", value, "lastUsed");
            return (Criteria) this;
        }

        public Criteria andLastUsedNotEqualTo(Date value) {
            addCriterion("last_used <>", value, "lastUsed");
            return (Criteria) this;
        }

        public Criteria andLastUsedGreaterThan(Date value) {
            addCriterion("last_used >", value, "lastUsed");
            return (Criteria) this;
        }

        public Criteria andLastUsedGreaterThanOrEqualTo(Date value) {
            addCriterion("last_used >=", value, "lastUsed");
            return (Criteria) this;
        }

        public Criteria andLastUsedLessThan(Date value) {
            addCriterion("last_used <", value, "lastUsed");
            return (Criteria) this;
        }

        public Criteria andLastUsedLessThanOrEqualTo(Date value) {
            addCriterion("last_used <=", value, "lastUsed");
            return (Criteria) this;
        }

        public Criteria andLastUsedIn(List<Date> values) {
            addCriterion("last_used in", values, "lastUsed");
            return (Criteria) this;
        }

        public Criteria andLastUsedNotIn(List<Date> values) {
            addCriterion("last_used not in", values, "lastUsed");
            return (Criteria) this;
        }

        public Criteria andLastUsedBetween(Date value1, Date value2) {
            addCriterion("last_used between", value1, value2, "lastUsed");
            return (Criteria) this;
        }

        public Criteria andLastUsedNotBetween(Date value1, Date value2) {
            addCriterion("last_used not between", value1, value2, "lastUsed");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_auth
     *
     * @mbg.generated do_not_delete_during_merge Sun Apr 05 19:40:51 AEST 2026
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_auth
     *
     * @mbg.generated Sun Apr 05 19:40:51 AEST 2026
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}