package com.alipay.usercenter.common.dal.auto.dataobject;

import java.util.Date;

public class UserSessionDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_session.session_id
     *
     * @mbg.generated Mon Dec 08 00:29:26 MYT 2025
     */
    private Long sessionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_session.user_id
     *
     * @mbg.generated Mon Dec 08 00:29:26 MYT 2025
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_session.email
     *
     * @mbg.generated Mon Dec 08 00:29:26 MYT 2025
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_session.full_name
     *
     * @mbg.generated Mon Dec 08 00:29:26 MYT 2025
     */
    private String fullName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_session.login_time
     *
     * @mbg.generated Mon Dec 08 00:29:26 MYT 2025
     */
    private Date loginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_session.last_active
     *
     * @mbg.generated Mon Dec 08 00:29:26 MYT 2025
     */
    private Date lastActive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_session.session_id
     *
     * @return the value of user_session.session_id
     *
     * @mbg.generated Mon Dec 08 00:29:26 MYT 2025
     */
    public Long getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_session.session_id
     *
     * @param sessionId the value for user_session.session_id
     *
     * @mbg.generated Mon Dec 08 00:29:26 MYT 2025
     */
    public void setSessionId(Long sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_session.user_id
     *
     * @return the value of user_session.user_id
     *
     * @mbg.generated Mon Dec 08 00:29:26 MYT 2025
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_session.user_id
     *
     * @param userId the value for user_session.user_id
     *
     * @mbg.generated Mon Dec 08 00:29:26 MYT 2025
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_session.email
     *
     * @return the value of user_session.email
     *
     * @mbg.generated Mon Dec 08 00:29:26 MYT 2025
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_session.email
     *
     * @param email the value for user_session.email
     *
     * @mbg.generated Mon Dec 08 00:29:26 MYT 2025
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_session.full_name
     *
     * @return the value of user_session.full_name
     *
     * @mbg.generated Mon Dec 08 00:29:26 MYT 2025
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_session.full_name
     *
     * @param fullName the value for user_session.full_name
     *
     * @mbg.generated Mon Dec 08 00:29:26 MYT 2025
     */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_session.login_time
     *
     * @return the value of user_session.login_time
     *
     * @mbg.generated Mon Dec 08 00:29:26 MYT 2025
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_session.login_time
     *
     * @param loginTime the value for user_session.login_time
     *
     * @mbg.generated Mon Dec 08 00:29:26 MYT 2025
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_session.last_active
     *
     * @return the value of user_session.last_active
     *
     * @mbg.generated Mon Dec 08 00:29:26 MYT 2025
     */
    public Date getLastActive() {
        return lastActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_session.last_active
     *
     * @param lastActive the value for user_session.last_active
     *
     * @mbg.generated Mon Dec 08 00:29:26 MYT 2025
     */
    public void setLastActive(Date lastActive) {
        this.lastActive = lastActive;
    }
}