package com.alipay.usercenter.common.dal.auto.dataobject;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserCardDetailDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_card_detail
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_card_detail
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_card_detail
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_detail
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    public UserCardDetailDOExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_detail
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_detail
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_detail
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_detail
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_detail
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_detail
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_detail
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_detail
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_detail
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_card_detail
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_card_detail
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserCardIdIsNull() {
            addCriterion("user_card_id is null");
            return (Criteria) this;
        }

        public Criteria andUserCardIdIsNotNull() {
            addCriterion("user_card_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserCardIdEqualTo(Object value) {
            addCriterion("user_card_id =", value, "userCardId");
            return (Criteria) this;
        }

        public Criteria andUserCardIdNotEqualTo(Object value) {
            addCriterion("user_card_id <>", value, "userCardId");
            return (Criteria) this;
        }

        public Criteria andUserCardIdGreaterThan(Object value) {
            addCriterion("user_card_id >", value, "userCardId");
            return (Criteria) this;
        }

        public Criteria andUserCardIdGreaterThanOrEqualTo(Object value) {
            addCriterion("user_card_id >=", value, "userCardId");
            return (Criteria) this;
        }

        public Criteria andUserCardIdLessThan(Object value) {
            addCriterion("user_card_id <", value, "userCardId");
            return (Criteria) this;
        }

        public Criteria andUserCardIdLessThanOrEqualTo(Object value) {
            addCriterion("user_card_id <=", value, "userCardId");
            return (Criteria) this;
        }

        public Criteria andUserCardIdIn(List<Object> values) {
            addCriterion("user_card_id in", values, "userCardId");
            return (Criteria) this;
        }

        public Criteria andUserCardIdNotIn(List<Object> values) {
            addCriterion("user_card_id not in", values, "userCardId");
            return (Criteria) this;
        }

        public Criteria andUserCardIdBetween(Object value1, Object value2) {
            addCriterion("user_card_id between", value1, value2, "userCardId");
            return (Criteria) this;
        }

        public Criteria andUserCardIdNotBetween(Object value1, Object value2) {
            addCriterion("user_card_id not between", value1, value2, "userCardId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andCardTypeIsNull() {
            addCriterion("card_type is null");
            return (Criteria) this;
        }

        public Criteria andCardTypeIsNotNull() {
            addCriterion("card_type is not null");
            return (Criteria) this;
        }

        public Criteria andCardTypeEqualTo(String value) {
            addCriterion("card_type =", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeNotEqualTo(String value) {
            addCriterion("card_type <>", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeGreaterThan(String value) {
            addCriterion("card_type >", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeGreaterThanOrEqualTo(String value) {
            addCriterion("card_type >=", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeLessThan(String value) {
            addCriterion("card_type <", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeLessThanOrEqualTo(String value) {
            addCriterion("card_type <=", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeLike(String value) {
            addCriterion("card_type like", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeNotLike(String value) {
            addCriterion("card_type not like", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeIn(List<String> values) {
            addCriterion("card_type in", values, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeNotIn(List<String> values) {
            addCriterion("card_type not in", values, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeBetween(String value1, String value2) {
            addCriterion("card_type between", value1, value2, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeNotBetween(String value1, String value2) {
            addCriterion("card_type not between", value1, value2, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardNetworkIsNull() {
            addCriterion("card_network is null");
            return (Criteria) this;
        }

        public Criteria andCardNetworkIsNotNull() {
            addCriterion("card_network is not null");
            return (Criteria) this;
        }

        public Criteria andCardNetworkEqualTo(String value) {
            addCriterion("card_network =", value, "cardNetwork");
            return (Criteria) this;
        }

        public Criteria andCardNetworkNotEqualTo(String value) {
            addCriterion("card_network <>", value, "cardNetwork");
            return (Criteria) this;
        }

        public Criteria andCardNetworkGreaterThan(String value) {
            addCriterion("card_network >", value, "cardNetwork");
            return (Criteria) this;
        }

        public Criteria andCardNetworkGreaterThanOrEqualTo(String value) {
            addCriterion("card_network >=", value, "cardNetwork");
            return (Criteria) this;
        }

        public Criteria andCardNetworkLessThan(String value) {
            addCriterion("card_network <", value, "cardNetwork");
            return (Criteria) this;
        }

        public Criteria andCardNetworkLessThanOrEqualTo(String value) {
            addCriterion("card_network <=", value, "cardNetwork");
            return (Criteria) this;
        }

        public Criteria andCardNetworkLike(String value) {
            addCriterion("card_network like", value, "cardNetwork");
            return (Criteria) this;
        }

        public Criteria andCardNetworkNotLike(String value) {
            addCriterion("card_network not like", value, "cardNetwork");
            return (Criteria) this;
        }

        public Criteria andCardNetworkIn(List<String> values) {
            addCriterion("card_network in", values, "cardNetwork");
            return (Criteria) this;
        }

        public Criteria andCardNetworkNotIn(List<String> values) {
            addCriterion("card_network not in", values, "cardNetwork");
            return (Criteria) this;
        }

        public Criteria andCardNetworkBetween(String value1, String value2) {
            addCriterion("card_network between", value1, value2, "cardNetwork");
            return (Criteria) this;
        }

        public Criteria andCardNetworkNotBetween(String value1, String value2) {
            addCriterion("card_network not between", value1, value2, "cardNetwork");
            return (Criteria) this;
        }

        public Criteria andLastFourIsNull() {
            addCriterion("last_four is null");
            return (Criteria) this;
        }

        public Criteria andLastFourIsNotNull() {
            addCriterion("last_four is not null");
            return (Criteria) this;
        }

        public Criteria andLastFourEqualTo(String value) {
            addCriterion("last_four =", value, "lastFour");
            return (Criteria) this;
        }

        public Criteria andLastFourNotEqualTo(String value) {
            addCriterion("last_four <>", value, "lastFour");
            return (Criteria) this;
        }

        public Criteria andLastFourGreaterThan(String value) {
            addCriterion("last_four >", value, "lastFour");
            return (Criteria) this;
        }

        public Criteria andLastFourGreaterThanOrEqualTo(String value) {
            addCriterion("last_four >=", value, "lastFour");
            return (Criteria) this;
        }

        public Criteria andLastFourLessThan(String value) {
            addCriterion("last_four <", value, "lastFour");
            return (Criteria) this;
        }

        public Criteria andLastFourLessThanOrEqualTo(String value) {
            addCriterion("last_four <=", value, "lastFour");
            return (Criteria) this;
        }

        public Criteria andLastFourLike(String value) {
            addCriterion("last_four like", value, "lastFour");
            return (Criteria) this;
        }

        public Criteria andLastFourNotLike(String value) {
            addCriterion("last_four not like", value, "lastFour");
            return (Criteria) this;
        }

        public Criteria andLastFourIn(List<String> values) {
            addCriterion("last_four in", values, "lastFour");
            return (Criteria) this;
        }

        public Criteria andLastFourNotIn(List<String> values) {
            addCriterion("last_four not in", values, "lastFour");
            return (Criteria) this;
        }

        public Criteria andLastFourBetween(String value1, String value2) {
            addCriterion("last_four between", value1, value2, "lastFour");
            return (Criteria) this;
        }

        public Criteria andLastFourNotBetween(String value1, String value2) {
            addCriterion("last_four not between", value1, value2, "lastFour");
            return (Criteria) this;
        }

        public Criteria andExpiryMonthIsNull() {
            addCriterion("expiry_month is null");
            return (Criteria) this;
        }

        public Criteria andExpiryMonthIsNotNull() {
            addCriterion("expiry_month is not null");
            return (Criteria) this;
        }

        public Criteria andExpiryMonthEqualTo(Short value) {
            addCriterion("expiry_month =", value, "expiryMonth");
            return (Criteria) this;
        }

        public Criteria andExpiryMonthNotEqualTo(Short value) {
            addCriterion("expiry_month <>", value, "expiryMonth");
            return (Criteria) this;
        }

        public Criteria andExpiryMonthGreaterThan(Short value) {
            addCriterion("expiry_month >", value, "expiryMonth");
            return (Criteria) this;
        }

        public Criteria andExpiryMonthGreaterThanOrEqualTo(Short value) {
            addCriterion("expiry_month >=", value, "expiryMonth");
            return (Criteria) this;
        }

        public Criteria andExpiryMonthLessThan(Short value) {
            addCriterion("expiry_month <", value, "expiryMonth");
            return (Criteria) this;
        }

        public Criteria andExpiryMonthLessThanOrEqualTo(Short value) {
            addCriterion("expiry_month <=", value, "expiryMonth");
            return (Criteria) this;
        }

        public Criteria andExpiryMonthIn(List<Short> values) {
            addCriterion("expiry_month in", values, "expiryMonth");
            return (Criteria) this;
        }

        public Criteria andExpiryMonthNotIn(List<Short> values) {
            addCriterion("expiry_month not in", values, "expiryMonth");
            return (Criteria) this;
        }

        public Criteria andExpiryMonthBetween(Short value1, Short value2) {
            addCriterion("expiry_month between", value1, value2, "expiryMonth");
            return (Criteria) this;
        }

        public Criteria andExpiryMonthNotBetween(Short value1, Short value2) {
            addCriterion("expiry_month not between", value1, value2, "expiryMonth");
            return (Criteria) this;
        }

        public Criteria andExpiryYearIsNull() {
            addCriterion("expiry_year is null");
            return (Criteria) this;
        }

        public Criteria andExpiryYearIsNotNull() {
            addCriterion("expiry_year is not null");
            return (Criteria) this;
        }

        public Criteria andExpiryYearEqualTo(Short value) {
            addCriterion("expiry_year =", value, "expiryYear");
            return (Criteria) this;
        }

        public Criteria andExpiryYearNotEqualTo(Short value) {
            addCriterion("expiry_year <>", value, "expiryYear");
            return (Criteria) this;
        }

        public Criteria andExpiryYearGreaterThan(Short value) {
            addCriterion("expiry_year >", value, "expiryYear");
            return (Criteria) this;
        }

        public Criteria andExpiryYearGreaterThanOrEqualTo(Short value) {
            addCriterion("expiry_year >=", value, "expiryYear");
            return (Criteria) this;
        }

        public Criteria andExpiryYearLessThan(Short value) {
            addCriterion("expiry_year <", value, "expiryYear");
            return (Criteria) this;
        }

        public Criteria andExpiryYearLessThanOrEqualTo(Short value) {
            addCriterion("expiry_year <=", value, "expiryYear");
            return (Criteria) this;
        }

        public Criteria andExpiryYearIn(List<Short> values) {
            addCriterion("expiry_year in", values, "expiryYear");
            return (Criteria) this;
        }

        public Criteria andExpiryYearNotIn(List<Short> values) {
            addCriterion("expiry_year not in", values, "expiryYear");
            return (Criteria) this;
        }

        public Criteria andExpiryYearBetween(Short value1, Short value2) {
            addCriterion("expiry_year between", value1, value2, "expiryYear");
            return (Criteria) this;
        }

        public Criteria andExpiryYearNotBetween(Short value1, Short value2) {
            addCriterion("expiry_year not between", value1, value2, "expiryYear");
            return (Criteria) this;
        }

        public Criteria andProviderIsNull() {
            addCriterion("provider is null");
            return (Criteria) this;
        }

        public Criteria andProviderIsNotNull() {
            addCriterion("provider is not null");
            return (Criteria) this;
        }

        public Criteria andProviderEqualTo(String value) {
            addCriterion("provider =", value, "provider");
            return (Criteria) this;
        }

        public Criteria andProviderNotEqualTo(String value) {
            addCriterion("provider <>", value, "provider");
            return (Criteria) this;
        }

        public Criteria andProviderGreaterThan(String value) {
            addCriterion("provider >", value, "provider");
            return (Criteria) this;
        }

        public Criteria andProviderGreaterThanOrEqualTo(String value) {
            addCriterion("provider >=", value, "provider");
            return (Criteria) this;
        }

        public Criteria andProviderLessThan(String value) {
            addCriterion("provider <", value, "provider");
            return (Criteria) this;
        }

        public Criteria andProviderLessThanOrEqualTo(String value) {
            addCriterion("provider <=", value, "provider");
            return (Criteria) this;
        }

        public Criteria andProviderLike(String value) {
            addCriterion("provider like", value, "provider");
            return (Criteria) this;
        }

        public Criteria andProviderNotLike(String value) {
            addCriterion("provider not like", value, "provider");
            return (Criteria) this;
        }

        public Criteria andProviderIn(List<String> values) {
            addCriterion("provider in", values, "provider");
            return (Criteria) this;
        }

        public Criteria andProviderNotIn(List<String> values) {
            addCriterion("provider not in", values, "provider");
            return (Criteria) this;
        }

        public Criteria andProviderBetween(String value1, String value2) {
            addCriterion("provider between", value1, value2, "provider");
            return (Criteria) this;
        }

        public Criteria andProviderNotBetween(String value1, String value2) {
            addCriterion("provider not between", value1, value2, "provider");
            return (Criteria) this;
        }

        public Criteria andProviderTokenIsNull() {
            addCriterion("provider_token is null");
            return (Criteria) this;
        }

        public Criteria andProviderTokenIsNotNull() {
            addCriterion("provider_token is not null");
            return (Criteria) this;
        }

        public Criteria andProviderTokenEqualTo(String value) {
            addCriterion("provider_token =", value, "providerToken");
            return (Criteria) this;
        }

        public Criteria andProviderTokenNotEqualTo(String value) {
            addCriterion("provider_token <>", value, "providerToken");
            return (Criteria) this;
        }

        public Criteria andProviderTokenGreaterThan(String value) {
            addCriterion("provider_token >", value, "providerToken");
            return (Criteria) this;
        }

        public Criteria andProviderTokenGreaterThanOrEqualTo(String value) {
            addCriterion("provider_token >=", value, "providerToken");
            return (Criteria) this;
        }

        public Criteria andProviderTokenLessThan(String value) {
            addCriterion("provider_token <", value, "providerToken");
            return (Criteria) this;
        }

        public Criteria andProviderTokenLessThanOrEqualTo(String value) {
            addCriterion("provider_token <=", value, "providerToken");
            return (Criteria) this;
        }

        public Criteria andProviderTokenLike(String value) {
            addCriterion("provider_token like", value, "providerToken");
            return (Criteria) this;
        }

        public Criteria andProviderTokenNotLike(String value) {
            addCriterion("provider_token not like", value, "providerToken");
            return (Criteria) this;
        }

        public Criteria andProviderTokenIn(List<String> values) {
            addCriterion("provider_token in", values, "providerToken");
            return (Criteria) this;
        }

        public Criteria andProviderTokenNotIn(List<String> values) {
            addCriterion("provider_token not in", values, "providerToken");
            return (Criteria) this;
        }

        public Criteria andProviderTokenBetween(String value1, String value2) {
            addCriterion("provider_token between", value1, value2, "providerToken");
            return (Criteria) this;
        }

        public Criteria andProviderTokenNotBetween(String value1, String value2) {
            addCriterion("provider_token not between", value1, value2, "providerToken");
            return (Criteria) this;
        }

        public Criteria andProviderCustomerIdIsNull() {
            addCriterion("provider_customer_id is null");
            return (Criteria) this;
        }

        public Criteria andProviderCustomerIdIsNotNull() {
            addCriterion("provider_customer_id is not null");
            return (Criteria) this;
        }

        public Criteria andProviderCustomerIdEqualTo(String value) {
            addCriterion("provider_customer_id =", value, "providerCustomerId");
            return (Criteria) this;
        }

        public Criteria andProviderCustomerIdNotEqualTo(String value) {
            addCriterion("provider_customer_id <>", value, "providerCustomerId");
            return (Criteria) this;
        }

        public Criteria andProviderCustomerIdGreaterThan(String value) {
            addCriterion("provider_customer_id >", value, "providerCustomerId");
            return (Criteria) this;
        }

        public Criteria andProviderCustomerIdGreaterThanOrEqualTo(String value) {
            addCriterion("provider_customer_id >=", value, "providerCustomerId");
            return (Criteria) this;
        }

        public Criteria andProviderCustomerIdLessThan(String value) {
            addCriterion("provider_customer_id <", value, "providerCustomerId");
            return (Criteria) this;
        }

        public Criteria andProviderCustomerIdLessThanOrEqualTo(String value) {
            addCriterion("provider_customer_id <=", value, "providerCustomerId");
            return (Criteria) this;
        }

        public Criteria andProviderCustomerIdLike(String value) {
            addCriterion("provider_customer_id like", value, "providerCustomerId");
            return (Criteria) this;
        }

        public Criteria andProviderCustomerIdNotLike(String value) {
            addCriterion("provider_customer_id not like", value, "providerCustomerId");
            return (Criteria) this;
        }

        public Criteria andProviderCustomerIdIn(List<String> values) {
            addCriterion("provider_customer_id in", values, "providerCustomerId");
            return (Criteria) this;
        }

        public Criteria andProviderCustomerIdNotIn(List<String> values) {
            addCriterion("provider_customer_id not in", values, "providerCustomerId");
            return (Criteria) this;
        }

        public Criteria andProviderCustomerIdBetween(String value1, String value2) {
            addCriterion("provider_customer_id between", value1, value2, "providerCustomerId");
            return (Criteria) this;
        }

        public Criteria andProviderCustomerIdNotBetween(String value1, String value2) {
            addCriterion("provider_customer_id not between", value1, value2, "providerCustomerId");
            return (Criteria) this;
        }

        public Criteria andCardholderNameIsNull() {
            addCriterion("cardholder_name is null");
            return (Criteria) this;
        }

        public Criteria andCardholderNameIsNotNull() {
            addCriterion("cardholder_name is not null");
            return (Criteria) this;
        }

        public Criteria andCardholderNameEqualTo(String value) {
            addCriterion("cardholder_name =", value, "cardholderName");
            return (Criteria) this;
        }

        public Criteria andCardholderNameNotEqualTo(String value) {
            addCriterion("cardholder_name <>", value, "cardholderName");
            return (Criteria) this;
        }

        public Criteria andCardholderNameGreaterThan(String value) {
            addCriterion("cardholder_name >", value, "cardholderName");
            return (Criteria) this;
        }

        public Criteria andCardholderNameGreaterThanOrEqualTo(String value) {
            addCriterion("cardholder_name >=", value, "cardholderName");
            return (Criteria) this;
        }

        public Criteria andCardholderNameLessThan(String value) {
            addCriterion("cardholder_name <", value, "cardholderName");
            return (Criteria) this;
        }

        public Criteria andCardholderNameLessThanOrEqualTo(String value) {
            addCriterion("cardholder_name <=", value, "cardholderName");
            return (Criteria) this;
        }

        public Criteria andCardholderNameLike(String value) {
            addCriterion("cardholder_name like", value, "cardholderName");
            return (Criteria) this;
        }

        public Criteria andCardholderNameNotLike(String value) {
            addCriterion("cardholder_name not like", value, "cardholderName");
            return (Criteria) this;
        }

        public Criteria andCardholderNameIn(List<String> values) {
            addCriterion("cardholder_name in", values, "cardholderName");
            return (Criteria) this;
        }

        public Criteria andCardholderNameNotIn(List<String> values) {
            addCriterion("cardholder_name not in", values, "cardholderName");
            return (Criteria) this;
        }

        public Criteria andCardholderNameBetween(String value1, String value2) {
            addCriterion("cardholder_name between", value1, value2, "cardholderName");
            return (Criteria) this;
        }

        public Criteria andCardholderNameNotBetween(String value1, String value2) {
            addCriterion("cardholder_name not between", value1, value2, "cardholderName");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_card_detail
     *
     * @mbg.generated do_not_delete_during_merge Sat Apr 25 14:00:44 AEST 2026
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_card_detail
     *
     * @mbg.generated Sat Apr 25 14:00:44 AEST 2026
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}